server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/erba_platform
    username: erba
    password: erba

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
    show-sql: true

auth:
  jwt:
    secret: "change-this-secret-key-must-be-at-least-32-characters-long"
    access-token-expiration-seconds: 900

