server:
  port: 8082

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/erba_platform
    username: erba
    password: erba
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: identity
        format_sql: true

  flyway:
    enabled: true
    schemas: identity
    default-schema: identity
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug