server:
  port: 8082

spring:
  application:
    name: identity-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/erba_platform
    username: erba
    password: erba
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: identity
        format_sql: true

  flyway:
    enabled: true
    schemas: identity
    default-schema: identity
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug

auth:
  jwt:
    secret: "change-this-secret-key-must-be-at-least-32-characters-long"
    access-token-expiration-seconds: 900

audit:
  client:
    base-url: "http://localhost:8083"
    source-service: "identity-service"
    internal-service-token: "dev-internal-audit-service-token"